### ISSUE TITLE
Drush launcher does not seem to work when called from remote client using drush aliases

### ISSUE THREAD

**Issue by martijnv** [dasginganinja/drush-launcher#16]
We use drush aliases to call drush (lanucher) from remote clients for e.g. deployments. Drush launcher works fine on the server itself, but we cannot get it to work when using drush aliases from a remote client.

The verbose output of drush on the client does not give any indication as to what is going wrong unfortunately.

**Comment by martijnv** [comment]
I wonder if it has anything to do with https://github.com/dasginganinja/drush-launcher/issues/14?

**Comment by martijnv** [comment]
Apparantly a drush alias call executes the following command:

 [info] Executing: ssh -t -o PasswordAuthentication=no user@www.domain.com 'drush status --uri=www.domain.com --root=/var/www/domain/htdocs' [0.04 sec, 8.21 MB]
 
And issue #14 seems to be about the call with --root and an equal sign not working properly?

**Comment by dasginganinja** [comment]
These do look connected @martijnv!  We're working on a fix for this and I think it's about solved!  I'll follow up when we have that issue solved. I'm certain that is the fix for this, too.

**Comment by dasginganinja** [comment]
@martijnv There is a new release -- v1.0.2 -- that should fix this. Can you please test with that release to see if it fixes your issue?

Thanks,
Tom

**Comment by martijnv** [comment]
Yes this works, as long as the "root" in the drush alias is the project root and not the docroot in which the index.php is located within the project (e.g. web / htdocs / etc).

In the drush alias documentation the root is explained like this:

"root: The Drupal root; must not be specified as a relative path."

**Comment by dasginganinja** [comment]
Okay so after taking a look at the code I found where this happening. When we assign drupalRoot to altRoot this occurs because we trust the root. Instead, we should be looking up in that path using our function for finding the Drupal root. 
I'll be pushing something up shortly here (hopefully a new version that fixes it).

**Comment by dasginganinja** [comment]
I didn't mean to close this. There is a new release v1.0.3 that I would ask if you could check out.
Thanks.

**Comment by bohemier** [comment]
v1.0.3 still doesn't work properly for me. When executing 

`drush st --root=/home/user/web/website.com/app/htdocs`

I get: Error: Drush executable not found at /home/user/web/website.com/app/htdocs/vendor/bin/drush

But executing 

`drush st --root=/home/user/web/website.com/app`

Works properly. The root should be pointing to where drupal's index.php and not the root of the project where composer.json is located.

thanks!

**Comment by bohemier** [comment]
oops... I didnt `go build` after checking out the tag 🥲

It works now :) Many thanks

**Comment by dasginganinja** [comment]
Since that seems to be working I'm going to close this issue. If y'all experience any other issues feel free to let us know!
